# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ublox_msgs/NavSTATUS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NavSTATUS(genpy.Message):
  _md5sum = "c59712aa2e07ac37df60d9b92f97d104"
  _type = "ublox_msgs/NavSTATUS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# NAV-STATUS (0x01 0x03)
# Receiver Navigation Status
#
# See important comments concerning validity of position and velocity given in
# section Navigation Output Filters.
#

uint8 CLASS_ID = 1
uint8 MESSAGE_ID = 3

uint32 iTOW             # GPS Millisecond time of week [ms]

uint8 gpsFix            # GPSfix Type, range 0..5
uint8 GPS_NO_FIX = 0
uint8 GPS_DEAD_RECKONING_ONLY = 1
uint8 GPS_2D_FIX = 2
uint8 GPS_3D_FIX = 3
uint8 GPS_GPS_DEAD_RECKONING_COMBINED = 4
uint8 GPS_TIME_ONLY_FIX = 6

uint8 flags             # Navigation Status Flags
uint8 FLAGS_GPSFIXOK = 1      # i.e. within DOP & ACC Masks
uint8 FLAGS_DIFFSOLN = 2      # DGPS used
uint8 FLAGS_WKNSET = 4        # Week Number valid
uint8 FLAGS_TOWSET = 8        # Time of Week valid

uint8 fixStat           # Fix Status Information
# DGPS Input Status:
uint8 DGPSISTAT_MASK = 1
uint8 DGPSISTAT_NONE = 0        # none
uint8 DGPSISTAT_PR_PRR = 1      # PR+PRR Correction
# map matching status:
uint8 MAPMATCHING_MASK = 192
uint8 MAPMATCHING_NONE = 0      # none
uint8 MAPMATCHING_VALID = 64    # valid, i.e. map matching data was received, but was too old
uint8 MAPMATCHING_USED = 128    # used, map matching data was applied
uint8 MAPMATCHING_DR = 192      # DR, map matching was the reason to enable the dead reckoning gpsFix type instead of publishing no fix

uint8 flags2            # further information about navigation output
# power safe mode state (Only for FW version >= 7.01; undefined otherwise)
uint8 PSMSTATE_ACQUISITION = 0                # ACQUISITION [or when psm disabled]
uint8 PSMSTATE_TRACKING = 1                   # TRACKING
uint8 PSMSTATE_POWER_OPTIMIZED_TRACKING = 2   # POWER OPTIMIZED TRACKING
uint8 PSMSTATE_INACTIVE = 3                   # INACTIVE

uint32 ttff             # Time to first fix (millisecond time tag)
uint32 msss             # Milliseconds since Startup / Reset
"""
  # Pseudo-constants
  CLASS_ID = 1
  MESSAGE_ID = 3
  GPS_NO_FIX = 0
  GPS_DEAD_RECKONING_ONLY = 1
  GPS_2D_FIX = 2
  GPS_3D_FIX = 3
  GPS_GPS_DEAD_RECKONING_COMBINED = 4
  GPS_TIME_ONLY_FIX = 6
  FLAGS_GPSFIXOK = 1
  FLAGS_DIFFSOLN = 2
  FLAGS_WKNSET = 4
  FLAGS_TOWSET = 8
  DGPSISTAT_MASK = 1
  DGPSISTAT_NONE = 0
  DGPSISTAT_PR_PRR = 1
  MAPMATCHING_MASK = 192
  MAPMATCHING_NONE = 0
  MAPMATCHING_VALID = 64
  MAPMATCHING_USED = 128
  MAPMATCHING_DR = 192
  PSMSTATE_ACQUISITION = 0
  PSMSTATE_TRACKING = 1
  PSMSTATE_POWER_OPTIMIZED_TRACKING = 2
  PSMSTATE_INACTIVE = 3

  __slots__ = ['iTOW','gpsFix','flags','fixStat','flags2','ttff','msss']
  _slot_types = ['uint32','uint8','uint8','uint8','uint8','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       iTOW,gpsFix,flags,fixStat,flags2,ttff,msss

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavSTATUS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.iTOW is None:
        self.iTOW = 0
      if self.gpsFix is None:
        self.gpsFix = 0
      if self.flags is None:
        self.flags = 0
      if self.fixStat is None:
        self.fixStat = 0
      if self.flags2 is None:
        self.flags2 = 0
      if self.ttff is None:
        self.ttff = 0
      if self.msss is None:
        self.msss = 0
    else:
      self.iTOW = 0
      self.gpsFix = 0
      self.flags = 0
      self.fixStat = 0
      self.flags2 = 0
      self.ttff = 0
      self.msss = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I4B2I().pack(_x.iTOW, _x.gpsFix, _x.flags, _x.fixStat, _x.flags2, _x.ttff, _x.msss))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.iTOW, _x.gpsFix, _x.flags, _x.fixStat, _x.flags2, _x.ttff, _x.msss,) = _get_struct_I4B2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I4B2I().pack(_x.iTOW, _x.gpsFix, _x.flags, _x.fixStat, _x.flags2, _x.ttff, _x.msss))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.iTOW, _x.gpsFix, _x.flags, _x.fixStat, _x.flags2, _x.ttff, _x.msss,) = _get_struct_I4B2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I4B2I = None
def _get_struct_I4B2I():
    global _struct_I4B2I
    if _struct_I4B2I is None:
        _struct_I4B2I = struct.Struct("<I4B2I")
    return _struct_I4B2I
