// Generated by gencpp from file bluedragon_propulsion/near_objects_X.msg
// DO NOT EDIT!


#ifndef BLUEDRAGON_PROPULSION_MESSAGE_NEAR_OBJECTS_X_H
#define BLUEDRAGON_PROPULSION_MESSAGE_NEAR_OBJECTS_X_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluedragon_propulsion
{
template <class ContainerAllocator>
struct near_objects_X_
{
  typedef near_objects_X_<ContainerAllocator> Type;

  near_objects_X_()
    : X_objects()  {
    }
  near_objects_X_(const ContainerAllocator& _alloc)
    : X_objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _X_objects_type;
  _X_objects_type X_objects;




  typedef boost::shared_ptr< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> const> ConstPtr;

}; // struct near_objects_X_

typedef ::bluedragon_propulsion::near_objects_X_<std::allocator<void> > near_objects_X;

typedef boost::shared_ptr< ::bluedragon_propulsion::near_objects_X > near_objects_XPtr;
typedef boost::shared_ptr< ::bluedragon_propulsion::near_objects_X const> near_objects_XConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bluedragon_propulsion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg'], 'bluedragon_propulsion': ['/home/tim/catkin_ws/src/bluedragon_propulsion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7a1b98aa7ff3484c531a329b3cf233";
  }

  static const char* value(const ::bluedragon_propulsion::near_objects_X_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7a1b98aa7ff348ULL;
  static const uint64_t static_value2 = 0x4c531a329b3cf233ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluedragon_propulsion/near_objects_X";
  }

  static const char* value(const ::bluedragon_propulsion::near_objects_X_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] X_objects \n\
";
  }

  static const char* value(const ::bluedragon_propulsion::near_objects_X_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X_objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct near_objects_X_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluedragon_propulsion::near_objects_X_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluedragon_propulsion::near_objects_X_<ContainerAllocator>& v)
  {
    s << indent << "X_objects[]" << std::endl;
    for (size_t i = 0; i < v.X_objects.size(); ++i)
    {
      s << indent << "  X_objects[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.X_objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEDRAGON_PROPULSION_MESSAGE_NEAR_OBJECTS_X_H
