// Generated by gencpp from file bluedragon_propulsion/propulsion.msg
// DO NOT EDIT!


#ifndef BLUEDRAGON_PROPULSION_MESSAGE_PROPULSION_H
#define BLUEDRAGON_PROPULSION_MESSAGE_PROPULSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bluedragon_propulsion
{
template <class ContainerAllocator>
struct propulsion_
{
  typedef propulsion_<ContainerAllocator> Type;

  propulsion_()
    : header()
    , left_throttle(0)
    , right_throttle(0)  {
    }
  propulsion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_throttle(0)
    , right_throttle(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _left_throttle_type;
  _left_throttle_type left_throttle;

   typedef int64_t _right_throttle_type;
  _right_throttle_type right_throttle;




  typedef boost::shared_ptr< ::bluedragon_propulsion::propulsion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluedragon_propulsion::propulsion_<ContainerAllocator> const> ConstPtr;

}; // struct propulsion_

typedef ::bluedragon_propulsion::propulsion_<std::allocator<void> > propulsion;

typedef boost::shared_ptr< ::bluedragon_propulsion::propulsion > propulsionPtr;
typedef boost::shared_ptr< ::bluedragon_propulsion::propulsion const> propulsionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluedragon_propulsion::propulsion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bluedragon_propulsion

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp': ['/home/tim/catkin_ws/src/ros_comm/clients/roscpp/msg'], 'bluedragon_propulsion': ['/home/tim/catkin_ws/src/bluedragon_propulsion/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluedragon_propulsion::propulsion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluedragon_propulsion::propulsion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluedragon_propulsion::propulsion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a774e17636e326c8db038b535586c623";
  }

  static const char* value(const ::bluedragon_propulsion::propulsion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa774e17636e326c8ULL;
  static const uint64_t static_value2 = 0xdb038b535586c623ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluedragon_propulsion/propulsion";
  }

  static const char* value(const ::bluedragon_propulsion::propulsion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int64 left_throttle\n\
int64 right_throttle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::bluedragon_propulsion::propulsion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_throttle);
      stream.next(m.right_throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct propulsion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluedragon_propulsion::propulsion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluedragon_propulsion::propulsion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_throttle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_throttle);
    s << indent << "right_throttle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEDRAGON_PROPULSION_MESSAGE_PROPULSION_H
