(cl:in-package ublox_msgs-msg)
(cl:export '(MASK-VAL
          MASK
          DYNMODEL-VAL
          DYNMODEL
          FIXMODE-VAL
          FIXMODE
          FIXEDALT-VAL
          FIXEDALT
          FIXEDALTVAR-VAL
          FIXEDALTVAR
          MINELEV-VAL
          MINELEV
          DRLIMIT-VAL
          DRLIMIT
          PDOP-VAL
          PDOP
          TDOP-VAL
          TDOP
          PACC-VAL
          PACC
          TACC-VAL
          TACC
          STATICHOLDTHRESH-VAL
          STATICHOLDTHRESH
          DGPSTIMEOUT-VAL
          DGPSTIMEOUT
          RESERVED2-VAL
          RESERVED2
          RESERVED3-VAL
          RESERVED3
          RESERVED4-VAL
          RESERVED4
))