(cl:in-package ublox_msgs-msg)
(cl:export '(VERSION-VAL
          VERSION
          MASK1-VAL
          MASK1
          RESERVED0-VAL
          RESERVED0
          RESERVED1-VAL
          RESERVED1
          RESERVED2-VAL
          RESERVED2
          MINSVS-VAL
          MINSVS
          MAXSVS-VAL
          MAXSVS
          MINCNO-VAL
          MINCNO
          RESERVED5-VAL
          RESERVED5
          INIFIX3D-VAL
          INIFIX3D
          RESERVED6-VAL
          RESERVED6
          RESERVED7-VAL
          RESERVED7
          ACKAIDING-VAL
          ACKAIDING
          WKNROLLOVER-VAL
          WKNROLLOVER
          RESERVED8-VAL
          RESERVED8
          RESERVED9-VAL
          RESERVED9
          RESERVED10-VAL
          RESERVED10
          USEPPP-VAL
          USEPPP
          AOPCFG-VAL
          AOPCFG
          RESERVED11-VAL
          RESERVED11
          RESERVED12-VAL
          RESERVED12
          AOPORBMAXERR-VAL
          AOPORBMAXERR
          RESERVED13-VAL
          RESERVED13
          RESERVED14-VAL
          RESERVED14
          RESERVED3-VAL
          RESERVED3
          RESERVED4-VAL
          RESERVED4
))